matrix:
  include:
    - name: "Xenial Linux with Python 3.6"
      os: linux
      dist: xenial
      sudo: required
      # explicit python as language: this force the use of virtual envs to use the right python version
      language: python
      python:
        - "3.6"
      before_install: 
        - python3 --version ; pip3 --version
      # Specific OS selection
      env: TARGETOS=linux

    - name: "macOS with Python 3.7"
      os: osx
      osx_image: xcode10.2
      language: shell
      before_install: 
        - python3 --version ; pip3 --version
      env: TARGETOS=osx

    - name: "Windows (Wine over Ubuntu Xenial) with Python 3.6"
      os: linux
      dist: xenial
      sudo: required
      # explicit python as language: this force the use of virtual envs to use the right python version
      language: python
      python:
        - "3.6"
      before_install:
        - python3 --version ; pip3 --version
      services:
        - docker
      env: TARGETOS=windows

# install dependencies depending on the OS
install: 
  - ./travis/install.sh $TARGETOS

script:
  - make init
  - make build

notifications:
  email: false
  webhooks: https://fathomless-fjord-24024.herokuapp.com/notify

before_deploy:
  - ./travis/before_deploy.sh $TARGETOS

# deploy step
deploy:
  # deploy on linux
  - provider: releases
    api_key:
      secure: $OAUTH
    file_glob: true
    file:
      - "final/*linux64-static.gz"
    draft: true
    skip_cleanup: true
    on:
      all_branches: true
      condition: "$TARGETOS = linux && $TRAVIS_BRANCH =~ ^master$|^release-.*$"
  
  # deploy on macos
  - provider: releases
    api_key:
      secure: $OAUTH
    file_glob: true
    file:
      - "final/*-app.tgz"
    draft: true
    skip_cleanup: true
    on:
      all_branches: true
      condition: "$TARGETOS = osx && $TRAVIS_BRANCH =~ ^master$|^release-.*$"
  
  # deploy on windows
  - provider: releases
    api_key:
      secure: $OAUTH
    file_glob: true
    file:
      - "final/*.exe"
    draft: true
    skip_cleanup: true
    on:
      all_branches: true
      condition: "$TARGETOS = windows && $TRAVIS_BRANCH =~ ^master$|^release-.*$"
