# main build matrix
matrix:
  include:
    - name: "Xenial Linux with Python 3.6"
      os: linux
      dist: xenial
      sudo: required
      # explicit python as language: this force the use of virtual envs to use the right python version
      language: python
      python:
        - "3.6"
      # Specific OS selection
      env: TARGETOS=linux

    - name: "macOS with Python 3.7"
      os: osx
      osx_image: xcode10.2
      language: shell
      env: TARGETOS=osx

    - name: "Windows (Wine over Ubuntu Xenial) with Python 3.6"
      os: linux
      dist: xenial
      sudo: required
      # explicit python as language: this force the use of virtual envs to use the right python version
      language: python
      python:
        - "3.6"
      services:
        - docker
      env: TARGETOS=windows

# Showing the python3 & pip versions for debug
before_install:
  - echo "Getting python & pip version"
  - python3 --version
  - pip3 --version

# install dependencies depending on the particular OS
install: 
  - ./travis/install.sh $TARGETOS

# build & test scripts
script:
  - make init
  - make build

# notifications (only via telegram)
notifications:
  email: false
  webhooks: https://fathomless-fjord-24024.herokuapp.com/notify

# make the apps for each OS
before_deploy:
  - export VERSION="$(git describe --tags --exact-match HEAD 2> /dev/null)"
  - ./travis/before_deploy.sh ${TARGETOS} ${VERSION}
  - ls -l ./final/

# deploy to Github
deploy:
  # deploy on linux
  - provider: releases
    api_key: $OAUTH
    file_glob: true
    draft: true
    overwrite: true
    skip_cleanup: true
    on:
      tags: true
    file:
      - "final/*"
