os: linux
dist: bionic
sudo: required
language: bash

before_script:
- sudo apt-get update -q
- sudo apt install -y python3 python3-pip python3-pyqt5 python3-pyqt5.qtquick qml-module-qtquick2 qml-module-qtquick-window2 qml-module-qtquick-layouts qml-module-qtquick-extras qml-module-qtquick-dialogs qml-module-qtquick-controls qml-module-qt-labs-folderlistmodel qml-module-qt-labs-settings
- pip3 install setuptools
- pip3 install pyqt5

script:
- python3 setup.py build
- sudo python3 setup.py install

notifications:
  webhooks: https://fathomless-fjord-24024.herokuapp.com/notify

before_deploy:
- bash python3 setup.py --command-packages=stdeb.command bdist_deb

deploy:
  provider: releases
  api_key:
    secure: mk0/aqvi4ky8RQ8h6vG+cw+wXHfLGyF8NmEigLuVtVbL5jz7zpvuO5i9HQkvsgNj7cXjUY2beepM17aF+LroLZUe21zpuhGib4k5rP9/Jxy8LBxIKMZZWg7HFqt5A29yAU4dYqPvV4Mig2nh0X1/HDcmnLLS8q1MFBPc655Sv//UERvlavvfXCL8rMjC+cX07eJoHpGJfyG+n6c6PiMKSnQ1sxjb1HADjP5HxdPHPl9BiKGkmKG2f92SKuR4FH5IfutcMWaCH+uSwzoE8RvqAEXspw0auLD1bLfbcatziR96DaK60DpSMUxrztImYnw+Yv/ratUHQjauk0qDOg+iPsem+OzoySutT3CLzENaeh54krKcZyc5rJFrhuF5mDbh2VnSZ1P/AszeYe/QUqCpbkzYIV8lWf7HMs+RfUec6qMpNTihIZjY5YyP6fff36N/jM50EZZNXdhifIpVdp3iOPeynktRvM2b/3elF6duerrPIUNlhmQHroQm3bU60Ksb+sceHHzuHIcKmPMTabg24Fvi36VCETn9rsyiilN2AIbjTGqR9TjOyg/Bp8QyCkvn1xNNtGqY2yI1AHn1LUMlkFwqsBc5jU+mJBOZYQcpmgQmJAt4Gnwi+1uOtR1tG+cF20YmRMhLqJQsKLQ/Jd0tyWlFhKmZHDc/jQ9VngZFXlI=
  file_glob: true
  file: "*.deb"
  draft: true
  skip_cleanup: true
  on:
    all_branches: true
    condition: "$TRAVIS_BRANCH =~ ^master|release$"
